version: '2'

services:
  server:
    image: chrislusf/seaweedfs:local
    ports:
      - 8333:8333
      - 9333:9333
      - 19333:19333
      - 8084:8080
      - 18084:18080
      - 8888:8888
      - 18888:18888
    command: "server -ip=server -filer -s3 -s3.auditLogConfig=/etc/seaweedfs/fluent.json -volume.max=0 -master.volumeSizeLimitMB=8 -volume.preStopSeconds=1"
    volumes:
      - ./fluent.json:/etc/seaweedfs/fluent.json
  fluent:
    image: fluent/fluentd:v1.14
    ports:
      - 24224:24224