name: "docker: test building container images"

on:
  pull_request:
  workflow_dispatch: []

concurrency:
  group: ${{ github.head_ref }}/container_test
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        platform: [ linux ]
        arch: [ amd64, arm, arm64, 386 ]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            chrislusf/seaweedfs
            ghcr.io/chrislusf/seaweedfs
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=seaweedfs
            org.opencontainers.image.vendor=Chris Lu
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: false
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}/${{ matrix.arch }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
